-- VELO PARTY POBE — schéma PostgreSQL Supabase
-- À exécuter dans Supabase > SQL Editor.

create table if not exists public.access_codes (
  id bigint generated by default as identity primary key,
  code_hash text not null unique,
  code_last4 text not null,
  ticket_type text not null,
  price integer not null check (price in (2000, 5000, 10000, 15000, 20000)),
  status text not null default 'AVAILABLE' check (status in ('AVAILABLE','USED')),
  created_at timestamptz not null default now(),
  used_at timestamptz
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  ticket_number text not null unique,
  public_token text not null unique,
  access_code_id bigint not null unique references public.access_codes(id),
  holder_name text not null,
  ticket_type text not null,
  price integer not null check (price in (2000, 5000, 10000, 15000, 20000)),
  created_at timestamptz not null default now(),
  checked_in_at timestamptz
);

create index if not exists idx_access_codes_status on public.access_codes(status);
create index if not exists idx_tickets_created_at on public.tickets(created_at desc);
create index if not exists idx_tickets_checked_in_at on public.tickets(checked_in_at);

-- RLS est activé afin qu'une clé anon/public ne puisse pas lire les données.
-- Le serveur utilise uniquement la clé service_role (jamais exposée au navigateur).
alter table public.access_codes enable row level security;
alter table public.tickets enable row level security;

-- RPC transactionnelle : un code ne peut produire qu'un seul ticket,
-- même si deux visiteurs tentent de l'utiliser simultanément.
create or replace function public.redeem_ticket(
  p_code_hash text,
  p_ticket_number text,
  p_public_token text,
  p_holder_name text
)
returns table (
  ticket_number text,
  public_token text,
  holder_name text,
  ticket_type text,
  price integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code public.access_codes%rowtype;
  v_created timestamptz;
begin
  select * into v_code
  from public.access_codes
  where code_hash = p_code_hash and status = 'AVAILABLE'
  for update;

  if not found then
    raise exception 'INVALID_OR_USED';
  end if;

  v_created := now();

  insert into public.tickets (
    ticket_number, public_token, access_code_id, holder_name,
    ticket_type, price, created_at
  ) values (
    p_ticket_number, p_public_token, v_code.id, p_holder_name,
    v_code.ticket_type, v_code.price, v_created
  );

  update public.access_codes
  set status = 'USED', used_at = v_created
  where id = v_code.id;

  return query
  select p_ticket_number, p_public_token, p_holder_name,
         v_code.ticket_type, v_code.price, v_created;
end;
$$;

-- RPC transactionnelle de validation : une seule validation peut réussir.
create or replace function public.checkin_ticket(p_public_token text)
returns table (
  ok boolean,
  error_code text,
  ticket_number text,
  holder_name text,
  ticket_type text,
  price integer,
  checked_in_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ticket public.tickets%rowtype;
  v_stamp timestamptz;
begin
  select * into v_ticket
  from public.tickets
  where public_token = p_public_token
  for update;

  if not found then
    return query select false, 'NOT_FOUND', null::text, null::text, null::text, null::integer, null::timestamptz;
    return;
  end if;

  if v_ticket.checked_in_at is not null then
    return query select false, 'ALREADY_USED', v_ticket.ticket_number, v_ticket.holder_name,
      v_ticket.ticket_type, v_ticket.price, v_ticket.checked_in_at;
    return;
  end if;

  v_stamp := now();
  update public.tickets set checked_in_at = v_stamp where id = v_ticket.id;

  return query select true, null::text, v_ticket.ticket_number, v_ticket.holder_name,
    v_ticket.ticket_type, v_ticket.price, v_stamp;
end;
$$;

-- Les fonctions sont appelées par le serveur avec service_role.
-- Aucun accès public n'est accordé aux tables.
revoke all on table public.access_codes from anon, authenticated;
revoke all on table public.tickets from anon, authenticated;
revoke all on function public.redeem_ticket(text,text,text,text) from public, anon, authenticated;
revoke all on function public.checkin_ticket(text) from public, anon, authenticated;
